apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: default
spec:
  secretName: gateway-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: frontend.94.130.54.145.sslip.io
  dnsNames:
    - frontend.94.130.54.145.sslip.io