apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: frontend-cert
spec:
  domains:
    - 34.54.201.1.sslip.io
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: frontend-cert
spec:
  rules:
    - host: 34.54.201.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-lb
                port:
                  number: 80
